# Generated by Django 4.2.25 on 2025-10-24 23:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('introduction', '0021_csrf_user_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('logged_in', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('failattempt', models.IntegerField(default=0)),
                ('lockout_cooldown', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AFSessionID',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CFUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('password2', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='CSRFUserTbl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('balance', models.IntegerField(default=0)),
                ('is_loggedin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SQLLabTable',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name='AF_admin',
        ),
        migrations.DeleteModel(
            name='AF_session_id',
        ),
        migrations.DeleteModel(
            name='CF_user',
        ),
        migrations.DeleteModel(
            name='CSRF_user_tbl',
        ),
        migrations.DeleteModel(
            name='sql_lab_table',
        ),
        migrations.AlterModelOptions(
            name='faang',
            options={'verbose_name': 'FAANG Company', 'verbose_name_plural': 'FAANG Companies'},
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickits',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authlogin',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='info',
            name='faang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='introduction.faang'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='otp',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='OTP must be a 6 digit string.', regex='^\\d{6}$')]),
        ),
        migrations.AddIndex(
            model_name='faang',
            index=models.Index(fields=['company'], name='introductio_company_43a8a8_idx'),
        ),
    ]
